apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 2
  labels:
    eda.nokia.com/role: edge
  name: adcgw2-ethernet-1-a-5-1
  namespace: clab-sroslabtest
  resourceVersion: "2078840"
  uid: 57c73c91-e725-4c1f-9ac2-dccada3838af
spec:
  description: inter-switch link to wanpe1
  enabled: true
  encapType: dot1q
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-a-5-1
    lacpPortPriority: 32768
    node: adcgw2
  type: interface
status:
  enabled: true
  lastChange: "2025-05-20T14:51:00.300Z"
  members:
  - enabled: true
    interface: ethernet-1-a-5-1
    lastChange: "2025-05-20T14:51:00.300Z"
    neighbors:
    - interface: 1/1/c2/1
      node: wanpe1
    node: adcgw2
    nodeInterface: 1/1/c5/1
    operationalState: up
    speed: 100G
  operationalState: up
  speed: 100G
