apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: adcgw1-ethernet-1-a-1-1
  namespace: clab-sroslabtest
  resourceVersion: "2078843"
  uid: 45f9bdd5-cfe9-43b4-aa5f-e6d635c81e42
spec:
  description: inter-switch link to aspine1
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-a-1-1
    lacpPortPriority: 32768
    node: adcgw1
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:04.500Z"
  members:
  - enabled: true
    interface: ethernet-1-a-1-1
    lastChange: "2025-05-19T08:24:04.500Z"
    neighbors:
    - interface: ethernet-1/27
      node: aspine1
    node: adcgw1
    nodeInterface: 1/1/c1/1
    operationalState: up
    speed: 100G
  operationalState: up
  speed: 100G
