apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: aleaf2-ethernet-1-28
  namespace: clab-sroslabtest
  resourceVersion: "2078856"
  uid: 3fd8cb88-8d11-476a-9444-8c6f0444f948
spec:
  description: inter-switch link to aspine2
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-28
    lacpPortPriority: 32768
    node: aleaf2
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.278Z"
  members:
  - enabled: true
    interface: ethernet-1-28
    lastChange: "2025-05-19T08:24:20.278Z"
    neighbors:
    - interface: ethernet-1/2
      node: aspine2
    node: aleaf2
    nodeInterface: ethernet-1/28
    operationalState: up
    speed: 25G
  operationalState: up
  speed: 25G
