apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: aleaf1-ethernet-1-27
  namespace: clab-sroslabtest
  resourceVersion: "2078910"
  uid: 509ec609-7946-475d-8001-1c59851dcea3
spec:
  description: inter-switch link to aspine1
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-27
    lacpPortPriority: 32768
    node: aleaf1
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.278Z"
  members:
  - enabled: true
    interface: ethernet-1-27
    lastChange: "2025-05-19T08:24:20.278Z"
    neighbors:
    - interface: ethernet-1/1
      node: aspine1
    node: aleaf1
    nodeInterface: ethernet-1/27
    operationalState: up
    speed: 25G
  operationalState: up
  speed: 25G
