apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: bspine2-ethernet-1-2
  namespace: clab-sroslabtest
  resourceVersion: "2078837"
  uid: 731d5ac8-6662-403e-8f79-baa850dc33b3
spec:
  description: inter-switch link to bleaf2
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-2
    lacpPortPriority: 32768
    node: bspine2
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.276Z"
  members:
  - enabled: true
    interface: ethernet-1-2
    lastChange: "2025-05-19T08:24:20.276Z"
    neighbors:
    - interface: ethernet-1/28
      node: bleaf2
    node: bspine2
    nodeInterface: ethernet-1/2
    operationalState: up
    speed: 400G
  operationalState: up
  speed: 400G
