apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: bspine2-ethernet-1-3
  namespace: clab-sroslabtest
  resourceVersion: "2078826"
  uid: 8c0c976d-2ad0-4418-ac5a-9ca0f487f453
spec:
  description: inter-switch link to bleaf3
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-3
    lacpPortPriority: 32768
    node: bspine2
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.276Z"
  members:
  - enabled: true
    interface: ethernet-1-3
    lastChange: "2025-05-19T08:24:20.276Z"
    neighbors:
    - interface: ethernet-1/28
      node: bleaf3
    node: bspine2
    nodeInterface: ethernet-1/3
    operationalState: up
    speed: 400G
  operationalState: up
  speed: 400G
