apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: bspine2-ethernet-1-27
  namespace: clab-sroslabtest
  resourceVersion: "2078866"
  uid: 1733d983-4103-45bc-a9dd-b9bc3457a317
spec:
  description: inter-switch link to bdcgw1
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-27
    lacpPortPriority: 32768
    node: bspine2
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.305Z"
  members:
  - enabled: true
    interface: ethernet-1-27
    lastChange: "2025-05-19T08:24:20.305Z"
    neighbors:
    - interface: 1/1/c2/1
      node: bdcgw1
    node: bspine2
    nodeInterface: ethernet-1/27
    operationalState: up
    speed: 400G
  operationalState: up
  speed: 400G
