apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: bspine1-ethernet-1-3
  namespace: clab-sroslabtest
  resourceVersion: "2078830"
  uid: 67a21656-eec0-43c9-92cc-ea2e9eabfa95
spec:
  description: inter-switch link to bleaf3
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-3
    lacpPortPriority: 32768
    node: bspine1
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.329Z"
  members:
  - enabled: true
    interface: ethernet-1-3
    lastChange: "2025-05-19T08:24:20.329Z"
    neighbors:
    - interface: ethernet-1/27
      node: bleaf3
    node: bspine1
    nodeInterface: ethernet-1/3
    operationalState: up
    speed: 400G
  operationalState: up
  speed: 400G
