apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: bspine1-ethernet-1-4
  namespace: clab-sroslabtest
  resourceVersion: "2078836"
  uid: 3d79b667-011b-44c0-a388-9303137e0a26
spec:
  description: inter-switch link to bleaf4
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-4
    lacpPortPriority: 32768
    node: bspine1
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.377Z"
  members:
  - enabled: true
    interface: ethernet-1-4
    lastChange: "2025-05-19T08:24:20.377Z"
    neighbors:
    - interface: ethernet-1/27
      node: bleaf4
    node: bspine1
    nodeInterface: ethernet-1/4
    operationalState: up
    speed: 400G
  operationalState: up
  speed: 400G
