apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: bspine1-ethernet-1-1
  namespace: clab-sroslabtest
  resourceVersion: "2078887"
  uid: bc280d48-1c3e-451b-8020-42cfd951a677
spec:
  description: inter-switch link to bleaf1
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-1
    lacpPortPriority: 32768
    node: bspine1
  type: interface
status:
  enabled: true
  lastChange: "2025-05-19T08:24:20.269Z"
  members:
  - enabled: true
    interface: ethernet-1-1
    lastChange: "2025-05-19T08:24:20.269Z"
    neighbors:
    - interface: ethernet-1/27
      node: bleaf1
    node: bspine1
    nodeInterface: ethernet-1/1
    operationalState: up
    speed: 400G
  operationalState: up
  speed: 400G
