apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  creationTimestamp: "2025-05-19T08:24:09Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: wanpe2-ethernet-1-a-3-1
  namespace: clab-sroslabtest
  resourceVersion: "2078892"
  uid: e24f0ea0-7d84-4430-ba63-8533e327ce25
spec:
  description: inter-switch link to bdcgw1
  enabled: true
  encapType: "null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
  - enabled: true
    interface: ethernet-1-a-3-1
    lacpPortPriority: 32768
    node: wanpe2
  type: interface
status:
  enabled: true
  lastChange: "2025-05-21T12:28:19.800Z"
  members:
  - enabled: true
    interface: ethernet-1-a-3-1
    lastChange: "2025-05-21T12:28:19.800Z"
    neighbors:
    - interface: 1/1/c6/1
      node: bdcgw1
    node: wanpe2
    nodeInterface: 1/1/c3/1
    operationalState: up
    speed: 100G
  operationalState: up
  speed: 100G
