apiVersion: services.eda.nokia.com/v1alpha1
kind: VirtualNetwork
metadata:
  creationTimestamp: "2025-05-22T09:50:51Z"
  generation: 3
  labels:
    eda.nokia.com/datacenter: b
  name: vnet10-dcb
  namespace: clab-sroslabtest
  resourceVersion: "2079229"
  uid: a262b415-ee41-4127-8de7-022fce359646
spec:
  bridgeDomains:
  - name: bd-vnet10-dcb
    spec:
      eviPool: evi-pool
      l2proxyARPND:
        proxyARP: false
        proxyND: false
        tableSize: 250
      macAging: 300
      macDuplicationDetection:
        action: StopLearning
        enabled: false
        holdDownTime: 9
        monitoringWindow: 3
        numMoves: 5
      tunnelIndexPool: tunnel-index-pool
      type: EVPNVXLAN
      vniPool: vni-pool
  bridgeInterfaces:
  - name: bd-if-vnet10-dcb
    spec:
      bridgeDomain: bd-vnet10-dcb
      interface: bleaf1-ethernet-1-1
      uplink:
        uplinkVLANID: pool
      vlanID: "10"
  irbInterfaces:
  - name: irb-if-vnet10-dcb
    spec:
      arpTimeout: 14400
      bfd:
        desiredMinTransmitInt: 1000000
        detectionMultiplier: 3
        enabled: false
        minEchoReceiveInterval: 1000000
        requiredMinReceive: 1000000
      bridgeDomain: bd-vnet10-dcb
      evpnRouteAdvertisementType:
        arpDynamic: true
        arpStatic: true
        ndDynamic: true
        ndStatic: true
      hostRoutePopulate:
        dynamic: true
        evpn: true
        static: true
      ipAddresses:
      - ipv4Address:
          ipPrefix: 10.2.0.1/30
      ipMTU: 1500
      ipv6RouterAdvertisement:
        currentHopLimit: 64
        enabled: false
        managedConfigurationFlag: false
        maxAdvertisementInterval: 600
        minAdvertisementInterval: 200
        otherConfigurationFlag: false
        reachableTime: 0
        retransmitTime: 0
        routerLifetime: 1800
      l3ProxyARPND:
        proxyARP: false
        proxyND: false
      learnUnsolicited: NONE
      router: router-vnet10-dcb
  protocols:
    bgp:
      bgpGroups:
      - name: bgp-vnet10-dcb-to-pe
        spec:
          exportPolicy:
          - policy-vnet10-dcb-accept-all
          ipv4Unicast:
            enabled: true
          multiHopMaxHop: 4
          peerAS:
            autonomousSystem: 65010
      bgpPeers:
      - name: bgp-peer-vnet10-dcb-dcgw1-to-pe
        spec:
          dynamicNeighbor: false
          group: bgp-vnet10-dcb-to-pe
          interface: rt-if-vnet10-dcb-dcgw1-to-pe
          interfaceKind: ROUTEDINTERFACE
          ipv4Unicast:
            enabled: true
          node: bdcgw1
          peerIP: 10.10.10.5
    routingPolicies:
      policies:
      - name: policy-vnet10-dcb-accept-all
        spec:
          defaultAction:
            policyResult: accept
          statement:
          - action:
              policyResult: accept
            match:
              protocol: BGP_EVPN
            name: policy-vnet10-dcb-accept-all
  routedInterfaces:
  - name: rt-if-vnet10-dcb-dcgw1-to-pe
    spec:
      arpTimeout: 14400
      bfd:
        desiredMinTransmitInt: 1000000
        detectionMultiplier: 3
        enabled: true
        minEchoReceiveInterval: 1000000
        requiredMinReceive: 1000000
      interface: bdcgw1-ethernet-1-a-5-1
      ipMTU: 1500
      ipv4Addresses:
      - ipPrefix: 10.10.10.4/31
        primary: true
      ipv6RouterAdvertisement:
        currentHopLimit: 64
        enabled: false
        managedConfigurationFlag: false
        maxAdvertisementInterval: 600
        minAdvertisementInterval: 200
        otherConfigurationFlag: false
        reachableTime: 0
        retransmitTime: 0
        routerLifetime: 1800
      l3ProxyARPND:
        proxyARP: true
        proxyND: true
      learnUnsolicited: NONE
      router: router-vnet10-dcb
      vlanID: "10"
      vlanPool: vlan-pool
  - name: rt-if-vnet10-dcb-dcgw2-to-pe
    spec:
      arpTimeout: 14400
      bfd:
        desiredMinTransmitInt: 1000000
        detectionMultiplier: 3
        enabled: true
        minEchoReceiveInterval: 1000000
        requiredMinReceive: 1000000
      interface: bdcgw2-ethernet-1-a-5-1
      ipMTU: 1500
      ipv4Addresses:
      - ipPrefix: 10.10.10.6/31
        primary: true
      ipv6RouterAdvertisement:
        currentHopLimit: 64
        enabled: false
        managedConfigurationFlag: false
        maxAdvertisementInterval: 600
        minAdvertisementInterval: 200
        otherConfigurationFlag: false
        reachableTime: 0
        retransmitTime: 0
        routerLifetime: 1800
      l3ProxyARPND:
        proxyARP: false
        proxyND: false
      learnUnsolicited: NONE
      router: router-vnet10-dcb
      vlanID: "10"
      vlanPool: vlan-pool
  routers:
  - name: router-vnet10-dcb
    spec:
      bgp:
        autonomousSystem: 63010
        ebgpPreference: 170
        enabled: true
        ibgpPreference: 170
        ipv4Unicast:
          enabled: true
        ipv6Unicast:
          enabled: false
        minWaitToAdvertise: 0
        rapidWithdrawl: true
        waitForFIBInstall: false
      eviPool: evi-pool
      routerID: 11.11.11.11
      tunnelIndexPool: tunnel-index-pool
      type: EVPNVXLAN
      vniPool: vni-pool
status:
  lastChange: "2025-05-23T15:21:53.000Z"
  nodes:
  - bleaf1
  - bdcgw1
  - bdcgw2
  numBGPPeers: 1
  numBGPPeersOperDown: 0
  numIRBInterfaces: 1
  numIRBInterfacesOperDown: 0
  numNodes: 3
  numRoutedInterfaces: 2
  numRoutedInterfacesOperDown: 0
  numSubInterfaces: 1
  numSubInterfacesOperDown: 0
  operationalState: up
