apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  creationTimestamp: "2025-05-19T08:24:14Z"
  generation: 2
  labels:
    eda.nokia.com/role: edge
  name: adcgw2-eth5-wanpe1-eth2
  namespace: clab-sroslabtest
  resourceVersion: "1593729"
  uid: fc5762c7-3506-433b-985c-6a15e727d599
spec:
  links:
  - local:
      interface: ethernet-1-a-5-1
      interfaceResource: adcgw2-ethernet-1-a-5-1
      node: adcgw2
    remote:
      interface: ethernet-1-a-2-1
      interfaceResource: wanpe1-ethernet-1-a-2-1
      node: wanpe1
    type: edge
