apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  creationTimestamp: "2025-05-19T08:24:15Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: adcgw1-eth2-aspine2-e1-27
  namespace: clab-sroslabtest
  resourceVersion: "1016035"
  uid: 377d2217-3d15-4b43-9b3f-f21716b07e24
spec:
  links:
  - local:
      interface: ethernet-1-a-2-1
      interfaceResource: adcgw1-ethernet-1-a-2-1
      node: adcgw1
    remote:
      interface: ethernet-1-27
      interfaceResource: aspine2-ethernet-1-27
      node: aspine2
    type: interSwitch
