apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  creationTimestamp: "2025-05-19T08:24:15Z"
  generation: 1
  labels:
    eda.nokia.com/role: interSwitch
  name: aspine1-e1-2-aleaf2-e1-27
  namespace: clab-sroslabtest
  resourceVersion: "1016038"
  uid: 58fb7763-d80e-48bf-af61-17aa571958f2
spec:
  links:
  - local:
      interface: ethernet-1-2
      interfaceResource: aspine1-ethernet-1-2
      node: aspine1
    remote:
      interface: ethernet-1-27
      interfaceResource: aleaf2-ethernet-1-27
      node: aleaf2
    type: interSwitch
